export { default as logo } from "./logo.png";
export { default as delivery } from "./delivryman.png";
export { default as heroBackground } from "./home-bg.png";
export { default as deliveryGuys } from "./deliveryGuys.png";
export { default as vision } from "./visionImg.png";
export { default as mission } from "./missionImg.png";
export { default as coreValue } from "./coreValueImg.png";
export { default as bolt } from "./bolt.png";
export { default as africanFemale } from "./africanFemale.png";
export { default as armingCountDown } from "./arming_countdown.png"
export { default as payment } from "./payments.png"
export { default as bike } from "./bike.png"
export { default as airplane } from "./airplane.png"
export { default as truck } from "./truck.png"
export { default as phone } from "./phone.png"
export { default as tiwtter } from "./tiwtter.png"
export { default as sarah } from "./sarah.png"
export { default as instgram } from "./instgram.png"
export { default as facebook } from "./facebook.png"
export { default as location } from "./location.png"
export { default as micheal } from "./micheal.png"
export { default as mail } from "./mail.png"
export { default as star } from "./Star.png"
export { default as whitehy } from "./whitehy.png"
export { default as greenhy } from "./greenhy.png"
export { default as logo2 } from "./logo2.png"	
export { default as google } from "./Google.png"
export { default as appleicon } from "./Apple.png"
export { default as signgoogle } from "./siginGoogle.png"
export { default as signfacebook } from "./siginFacebook.png"